services:
  app:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    env_file:
      - ./.devcontainer/.env
  neo4j:
    env_file: !override
      - ./.devcontainer/.neo4j.env